# Generated by Django 5.1.6 on 2025-07-08 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hidden_profile", "0010_alter_postsurvey_llm_collaboration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="grant_funding_secured",
            new_name="grant_funding_secured_po",
        ),
    ]
