# Generated by Django 5.1.6 on 2025-04-01 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.IntegerField()),
                ('winner', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('number_of_courses_taught', models.CharField(max_length=10)),
                ('student_teaching_evaluations', models.CharField(max_length=10)),
                ('number_of_peer_reviewed_publications', models.CharField(max_length=10)),
                ('citations', models.CharField(max_length=10)),
                ('service_on_editorial_boards', models.CharField(max_length=10)),
                ('conference_organization_roles', models.CharField(max_length=100)),
                ('undergraduate_mentorship_success', models.CharField(max_length=100)),
                ('graduate_thesis_supervision', models.CharField(max_length=100)),
                ('curriculum_development', models.CharField(max_length=100)),
                ('teaching_awards', models.CharField(max_length=100)),
                ('grant_funding_secured', models.CharField(max_length=100)),
                ('impact_of_research_publications', models.CharField(max_length=100)),
                ('interdisciplinary_research', models.CharField(max_length=100)),
                ('research_awards', models.CharField(max_length=100)),
                ('invited_talks', models.CharField(max_length=100)),
                ('industry_collaboration', models.CharField(max_length=100)),
                ('university_committee_service', models.CharField(max_length=100)),
                ('diversity_and_inclusion_initiatives', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('description', models.CharField(default='Not set', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=100)),
                ('qualification_study_id', models.CharField(max_length=100)),
                ('qualification_seesion_id', models.CharField(max_length=100)),
                ('formal_study_id', models.CharField(max_length=100)),
                ('formal_session_id', models.CharField(max_length=100)),
                ('avatar_color', models.CharField(default=None, max_length=100, null=True)),
                ('avatar_name', models.CharField(default=None, max_length=100, null=True)),
                ('group_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('description', models.CharField(default='Not set', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_size', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.condition')),
                ('active_participants', models.ManyToManyField(blank=True, related_name='active_groups', to='hidden_profile.participant')),
                ('participants', models.ManyToManyField(related_name='groups', to='hidden_profile.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.PositiveIntegerField()),
                ('candidatePair', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='hidden_profile.group')),
            ],
            options={
                'unique_together': {('group', 'turn_number')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hidden_profile.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.participant')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hidden_profile.turn')),
            ],
        ),
        migrations.CreateModel(
            name='LlmMessage',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_messages', to='hidden_profile.group')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_private_messages', to='hidden_profile.participant')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_messages', to='hidden_profile.turn')),
            ],
        ),
        migrations.CreateModel(
            name='InitialRecord',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_records', to='hidden_profile.candidateprofile')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_records', to='hidden_profile.participant')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_records', to='hidden_profile.turn')),
            ],
        ),
        migrations.CreateModel(
            name='FormalRecord',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_records', to='hidden_profile.candidateprofile')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_records', to='hidden_profile.participant')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_records', to='hidden_profile.turn')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTurn',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.participant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.role')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.turn')),
            ],
            options={
                'unique_together': {('participant', 'turn')},
            },
        ),
    ]
