# Generated by Django 5.1.6 on 2025-02-09 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('pair', models.IntegerField()),
                ('number_of_courses_taught', models.IntegerField()),
                ('student_teaching_evaluations', models.FloatField()),
                ('number_of_peer_reviewed_publications', models.IntegerField()),
                ('citation_impact', models.FloatField()),
                ('service_on_editorial_boards', models.BooleanField()),
                ('conference_organization_roles', models.BooleanField()),
                ('undergraduate_mentorship_success', models.BooleanField()),
                ('graduate_thesis_supervision', models.BooleanField()),
                ('curriculum_development', models.BooleanField()),
                ('teaching_awards', models.BooleanField()),
                ('grant_funding_secured', models.BooleanField()),
                ('impact_of_research_publications', models.BooleanField()),
                ('interdisciplinary_research', models.BooleanField()),
                ('research_awards', models.BooleanField()),
                ('invited_talks', models.BooleanField()),
                ('industry_collaboration', models.BooleanField()),
                ('university_committee_service', models.BooleanField()),
                ('diversity_and_inclusion_initiatives', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_size', models.PositiveIntegerField(default=3)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=100)),
                ('qualification_study_id', models.CharField(max_length=100)),
                ('qualification_seesion_id', models.CharField(max_length=100)),
                ('formal_study_id', models.CharField(max_length=100)),
                ('formal_session_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hidden_profile.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='active_participants',
            field=models.ManyToManyField(blank=True, related_name='active_groups', to='hidden_profile.participant'),
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='groups', to='hidden_profile.participant'),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('candidate_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_1', to='hidden_profile.candidateprofile')),
                ('candidate_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_2', to='hidden_profile.candidateprofile')),
                ('candidate_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_3', to='hidden_profile.candidateprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='hidden_profile.group')),
            ],
            options={
                'unique_together': {('group', 'turn_number')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hidden_profile.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.participant')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hidden_profile.turn')),
            ],
        ),
        migrations.CreateModel(
            name='LlmMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_messages', to='hidden_profile.group')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_private_messages', to='hidden_profile.participant')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_messages', to='hidden_profile.turn')),
            ],
        ),
        migrations.CreateModel(
            name='FormalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_records', to='hidden_profile.participant')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_records', to='hidden_profile.turn')),
            ],
        ),
        migrations.CreateModel(
            name='PariticipantTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.participant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.role')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hidden_profile.turn')),
            ],
            options={
                'unique_together': {('participant', 'turn')},
            },
        ),
    ]
