# Generated by Django 5.1.6 on 2025-04-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='avatar_name',
            new_name='avatar_animal',
        ),
    ]
