# Generated by Django 5.1.6 on 2025-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0002_group_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='description',
            field=models.CharField(default='Not set', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default='Not set', max_length=100),
        ),
    ]
