# Generated by Django 5.1.6 on 2025-04-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0002_rename_avatar_name_participant_avatar_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='participant',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
