# Generated by Django 5.1.6 on 2025-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0003_condition_description_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='condition',
            name='_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
