# Generated by Django 5.1.6 on 2025-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0003_participant_bonus_participant_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmessage',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
    ]
