# Generated by Django 5.1.6 on 2025-05-08 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0004_llmmessage_is_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mental_demand', models.IntegerField()),
                ('physical_demand', models.IntegerField()),
                ('temporal_demand', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('effort', models.IntegerField()),
                ('frustration', models.IntegerField()),
                ('dialogue_management', models.IntegerField()),
                ('information_pooling', models.IntegerField()),
                ('reaching_consensus', models.IntegerField()),
                ('task_division', models.IntegerField()),
                ('time_management', models.IntegerField()),
                ('technical_coordination', models.IntegerField()),
                ('reciprocal_interaction', models.IntegerField()),
                ('individual_task_orientation', models.IntegerField()),
                ('llm_collaboration', models.IntegerField()),
                ('llm_satisfaction', models.IntegerField()),
                ('llm_quality', models.IntegerField()),
                ('llm_recommendation', models.IntegerField()),
                ('llm_future_use', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_surveys', to='hidden_profile.participant')),
            ],
        ),
    ]
