# Generated by Django 5.1.6 on 2025-06-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hidden_profile", "0004_llmmessage_is_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="auto_llm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="complete_initial",
            field=models.BooleanField(default=False),
        ),
    ]
