# Generated by Django 5.1.6 on 2025-02-11 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0004_remove_condition_id_remove_role_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='group',
        ),
        migrations.AddField(
            model_name='participant',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
