# Generated by Django 5.1.6 on 2025-02-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0005_remove_participant_group_participant_group_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PariticipantTurn',
            new_name='ParticipantTurn',
        ),
    ]
