# Generated by Django 5.1.6 on 2025-06-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hidden_profile", "0005_participant_auto_llm_participant_complete_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmessage",
            name="is_intervention_analysis",
            field=models.BooleanField(default=False),
        ),
    ]
