# Generated by Django 5.1.6 on 2025-06-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hidden_profile", "0006_llmmessage_is_intervention_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmessage",
            name="type_of_intervention",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
