# Generated by Django 5.1.6 on 2025-02-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0006_rename_pariticipantturn_participantturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='Name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
