# Generated by Django 5.1.6 on 2025-06-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0005_postsurvey'),
        ('hidden_profile', '0007_llmmessage_type_of_intervention'),
    ]

    operations = [
    ]
