# Generated by Django 5.1.6 on 2025-02-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0007_candidateprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='citation_impact',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='citations',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='winner',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='conference_organization_roles',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='curriculum_development',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='diversity_and_inclusion_initiatives',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='graduate_thesis_supervision',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='grant_funding_secured',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='impact_of_research_publications',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='industry_collaboration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='interdisciplinary_research',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='invited_talks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='number_of_courses_taught',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='number_of_peer_reviewed_publications',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='research_awards',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='service_on_editorial_boards',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='student_teaching_evaluations',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='teaching_awards',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='undergraduate_mentorship_success',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='university_committee_service',
            field=models.CharField(max_length=100),
        ),
    ]
