# Generated by Django 5.1.6 on 2025-06-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0008_merge_20250615_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsurvey',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='frustration',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='mental_demand',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='physical_demand',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='temporal_demand',
        ),
        migrations.AddField(
            model_name='llmmessage',
            name='input_messages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='quori_included',
            field=models.BooleanField(default=False),
        ),
    ]
