# Generated by Django 5.1.6 on 2025-02-13 02:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0008_rename_name_candidateprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
