# Generated by Django 5.1.6 on 2025-02-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0009_remove_candidateprofile_id_candidateprofile__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='candidate_1',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='candidate_2',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='candidate_3',
        ),
    ]
