# Generated by Django 5.1.6 on 2025-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0009_remove_postsurvey_effort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsurvey',
            name='llm_collaboration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='llm_future_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='llm_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='llm_recommendation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='llm_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
