# Generated by Django 5.1.6 on 2025-02-13 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0010_remove_turn_candidate_1_remove_turn_candidate_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formalrecord',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='llmmessage',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='_id',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='id',
        ),
        migrations.AddField(
            model_name='turn',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
