# Generated by Django 5.1.6 on 2025-07-08 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hidden_profile", "0010_alter_postsurvey_llm_collaboration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="diversity_and_inclusion_initiatives",
            new_name="research_coverage",
        ),
        migrations.RenameField(
            model_name="candidateprofile",
            old_name="impact_of_research_publications",
            new_name="reviewer_activity",
        ),
    ]
