# Generated by Django 5.1.6 on 2025-09-17 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0011_rename_grant_funding_secured_po_candidateprofile_grant_funding_secured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSurvey',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_knowledge', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_surveys', to='hidden_profile.participant')),
            ],
        ),
    ]
