# Generated by Django 5.1.6 on 2025-02-13 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0011_rename_id_formalrecord__id_rename_id_llmmessage__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantturn',
            name='id',
        ),
        migrations.AddField(
            model_name='participantturn',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
