# Generated by Django 5.1.6 on 2025-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0012_remove_participantturn_id_participantturn__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='avatar_color',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='avatar_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
