# Generated by Django 5.1.6 on 2025-09-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0013_postsurveyllm_postsurveynasa_postsurveytask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsurveynasa',
            name='physical_demand',
        ),
        migrations.RemoveField(
            model_name='postsurveytask',
            name='task_division',
        ),
        migrations.RemoveField(
            model_name='postsurveytask',
            name='technical_coordination',
        ),
    ]
