# Generated by Django 5.1.6 on 2025-09-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0014_remove_postsurveynasa_physical_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsurveyllm',
            name='llm_alternatives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsurveyllm',
            name='llm_encouragement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsurveyllm',
            name='llm_summary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsurveyllm',
            name='open_ended_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
