# Generated by Django 5.1.6 on 2025-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0015_postsurveyllm_llm_alternatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='citations',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='number_of_courses_taught',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='number_of_peer_reviewed_publications',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='service_on_editorial_boards',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='student_teaching_evaluations',
            field=models.CharField(max_length=100),
        ),
    ]
