# Generated by Django 5.1.6 on 2025-11-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0016_alter_candidateprofile_citations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='difficult',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
