# Generated by Django 5.1.6 on 2025-11-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0017_candidateprofile_difficult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
