# Generated by Django 5.1.6 on 2025-12-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0018_group_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='curriculum_development',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='graduate_thesis_supervision',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='invited_talks',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='number_of_courses_taught',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='research_awards',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='reviewer_activity',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='student_teaching_evaluations',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='university_committee_service',
        ),
    ]
