# Generated by Django 5.1.6 on 2025-12-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0019_remove_candidateprofile_curriculum_development_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='industry_collaboration',
            new_name='collaborations',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='conference_organization_roles',
            new_name='conference_organization',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='grant_funding_secured',
            new_name='funding',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='interdisciplinary_research',
            new_name='interdisciplinarity',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='undergraduate_mentorship_success',
            new_name='mentorship',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='number_of_peer_reviewed_publications',
            new_name='publications',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='service_on_editorial_boards',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='teaching_awards',
            new_name='teaching',
        ),
    ]
