# Generated by Django 5.1.6 on 2026-01-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hidden_profile', '0020_rename_industry_collaboration_candidateprofile_collaborations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='service',
            new_name='editorial_service',
        ),
    ]
